# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.

HEADERS += ../test/BaseTest.h \
    ../test/ConnectionPoolTest.h \
    ../test/EngineModelSelector.h \
    ../test/RunnableHandler.h \
    ../test/condition/ConnectorTest.h \
    ../test/loader/DbLoaderTest.h \
    ../test/mysqlentity/mysqldefaulttestint.h \
    ../test/mysqlentity/mysqldefaultteststr.h \
    ../test/mysqlentity/mysqldefaulttesttime.h \
    ../test/mysqlentity/mysqlentityinclude.h \
    ../test/mysqlentity/mysqltest1.h \
    ../test/mysqlentity/mysqltest2.h \
    ../test/mysqlentity/mysqltest3.h \
    ../test/query/BaseQueryTest.h \
    ../test/query/DeleteTest.h \
    ../test/query/InsertIntoSelectTest.h \
    ../test/query/InsertTest.h \
    ../test/query/JoinTest.h \
    ../test/query/SelectTest.h \
    ../test/query/UpdateTest.h \
    ../test/query/LoggingTest.h \
    ../test/query/UpsertTest.h \
    ../test/sqliteentity/sqlitedefaulttestint.h \
    ../test/sqliteentity/sqlitedefaultteststr.h \
    ../test/sqliteentity/sqliteentityinclude.h \
    ../test/sqliteentity/sqlitetest1.h \
    ../test/sqliteentity/sqlitetest2.h \
    ../test/sqliteentity/sqlitetest3.h \
    ../test/sqlserverentity/sqlserverdefaulttestbytes.h \
    ../test/sqlserverentity/sqlserverdefaulttestint.h \
    ../test/sqlserverentity/sqlserverdefaultteststr.h \
    ../test/sqlserverentity/sqlserverdefaulttesttime.h \
    ../test/sqlserverentity/sqlserverentityinclude.h \
    ../test/sqlserverentity/sqlservertest1.h \
    ../test/sqlserverentity/sqlservertest2.h \
    ../test/sqlserverentity/sqlservertest3.h

SOURCES += ../test/BaseTest.cpp \
    ../test/ConnectionPoolTest.cpp \
    ../test/main.cpp \
    ../test/condition/ConnectorTest.cpp \
    ../test/loader/DbLoaderTest.cpp \
    ../test/mysqlentity/mysqlentityinclude.cpp \
    ../test/query/BaseQueryTest.cpp \
    ../test/query/DeleteTest.cpp \
    ../test/query/InsertIntoSelectTest.cpp \
    ../test/query/InsertTest.cpp \
    ../test/query/JoinTest.cpp \
    ../test/query/SelectTest.cpp \
    ../test/query/UpdateTest.cpp \
    ../test/query/LoggingTest.cpp \
    ../test/query/UpsertTest.cpp \
    ../test/sqliteentity/sqliteentityinclude.cpp \
    ../test/sqlserverentity/sqlserverentityinclude.cpp
