# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.

HEADERS += ../test/BaseTest.h \
    ../test/ConnectionPoolTest.h \
    ../test/query/UpdateTest.h \
    ../test/query/SqliteWriteSyncTest.h \
    ../test/query/SelectTest.h \
    ../test/query/JoinTest.h \
    ../test/query/InsertTest.h \
    ../test/query/InsertIntoSelectTest.h \
    ../test/query/DeleteTest.h \
    ../test/query/BaseQueryTest.h \
    ../test/loader/DbLoaderTest.h \
    ../test/sqliteentity/SqliteDefaultTestInt.h \
    ../test/sqliteentity/SqliteDefaultTestStr.h \
    ../test/sqliteentity/SqliteTest1.h \
    ../test/sqliteentity/SqliteTest2.h \
    ../test/sqliteentity/SqliteTest3.h \
    ../test/sqliteentity/SqliteEntityInclude.h \
    ../test/sqliteentity/SqliteConfig.h \
    ../test/condition/ConnectorTest.h \
    ../test/mysqlentity/MysqlDefaultTestInt.h \
    ../test/mysqlentity/MysqlDefaultTestStr.h \
    ../test/mysqlentity/MysqlDefaultTestTime.h \
    ../test/mysqlentity/MysqlTest1.h \
    ../test/mysqlentity/MysqlTest2.h \
    ../test/mysqlentity/MysqlTest3.h \
    ../test/mysqlentity/MysqlTest4.h \
    ../test/mysqlentity/MysqlConfig.h \
    ../test/mysqlentity/MysqlEntityInclude.h \
    ../test/sqlserverentity/SqlServerDefaultTestBytes.h \
    ../test/sqlserverentity/SqlServerDefaultTestInt.h \
    ../test/sqlserverentity/SqlServerDefaultTestStr.h \
    ../test/sqlserverentity/SqlServerDefaultTestTime.h \
    ../test/sqlserverentity/SqlServerTest1.h \
    ../test/sqlserverentity/SqlServerTest2.h \
    ../test/sqlserverentity/SqlServerTest3.h \
    ../test/sqlserverentity/SqlServerConfig.h \
    ../test/sqlserverentity/SqlServerEntityInclude.h
SOURCES += ../test/BaseTest.cpp \
    ../test/ConnectionPoolTest.cpp \
    ../test/main.cpp \
    ../test/query/BaseQueryTest.cpp \
    ../test/query/DeleteTest.cpp \
    ../test/query/InsertIntoSelectTest.cpp \
    ../test/query/InsertTest.cpp \
    ../test/query/JoinTest.cpp \
    ../test/query/SelectTest.cpp \
    ../test/query/SqliteWriteSyncTest.cpp \
    ../test/query/UpdateTest.cpp \
    ../test/loader/DbLoaderTest.cpp \
    ../test/condition/ConnectorTest.cpp \
    ../test/sqliteentity/SqliteEntityInclude.cpp \
    ../test/mysqlentity/MysqlEntityInclude.cpp \
    ../test/sqlserverentity/SqlServerEntityInclude.cpp
