# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# ----------------------------------------------------


HEADERS += ./sqlservertest1.h \
    ./sqlservertest2.h \
    ./sqlservertest3.h \
    ./sqlserverdefaulttestint.h \
    ./sqlserverdefaulttesttime.h \
    ./sqlserverdefaultteststr.h \
    ./sqlserverdefaulttestbytes.h \
    ./sqlserverentityinclude.h
SOURCES += ./sqlserverentityinclude.cpp
