# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# ----------------------------------------------------


set(ENTITY_FILE_LIST
    ${CMAKE_CURRENT_LIST_DIR}/sqlserverentityinclude.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlserverentityinclude.cpp

    ${CMAKE_CURRENT_LIST_DIR}/sqlservertest1.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlservertest2.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlservertest3.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlserverdefaulttestint.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlserverdefaulttesttime.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlserverdefaultteststr.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlserverdefaulttestbytes.h
)