# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS += ./qtdao/src/ConnectionPool.h \
    ./qtdao/src/dao.h \
    ./qtdao/src/DbConfig.h \
    ./qtdao/src/DbExceptionHandler.h \
    ./qtdao/src/DbLoader.h \
    ./qtdao/src/query/BaseQuery.h \
    ./qtdao/src/query/InsertIntoSelect.h \
    ./qtdao/src/query/Delete.h \
    ./qtdao/src/query/Insert.h \
    ./qtdao/src/query/Join.h \
    ./qtdao/src/query/Select.h \
    ./qtdao/src/query/Update.h \
    ./qtdao/src/dbclients/AbstractClient.h \
    ./qtdao/src/dbclients/MysqlClient.h \
    ./qtdao/src/dbclients/SqliteClient.h \
    ./qtdao/src/dbclients/SqlServerClient.h \
    ./qtdao/src/condition/ConditionOperator.h \
    ./qtdao/src/condition/Connector.h \
    ./qtdao/src/condition/ConnectorData.h \
    ./qtdao/src/condition/ConditionConstraint.h \
    ./qtdao/src/condition/EntityConditionData.h \
    ./qtdao/src/condition/EntityField.h \
    ./qtdao/src/condition/EntityCondition.h \
    ./qtdao/src/condition/FunctionConditionData.h \
    ./qtdao/src/condition/FunctionCondition.h \
    ./qtdao/src/builder/BaseQueryBuilder.h \
    ./qtdao/src/builder/CountBuilder.h \
    ./qtdao/src/builder/DeleteBuilder.h \
    ./qtdao/src/builder/InsertBuilder.h \
    ./qtdao/src/builder/InsertIntoSelectBuilder.h \
    ./qtdao/src/builder/JoinBuilder.h \
    ./qtdao/src/builder/RecursiveQueryBuilder.h \
    ./qtdao/src/builder/SelectBuilder.h \
    ./qtdao/src/builder/UpdateBuilder.h \
    ./qtdao/src/macro/macro.h
SOURCES += ./qtdao/src/ConnectionPool.cpp \
    $$PWD/src/builder/BaseQueryBuilder.cpp \
    ./qtdao/src/DbLoader.cpp \
    ./qtdao/src/qtdao.cpp \
    ./qtdao/src/query/BaseQuery.cpp \
    ./qtdao/src/dbclients/AbstractClient.cpp \
    ./qtdao/src/dbclients/MysqlClient.cpp \
    ./qtdao/src/dbclients/SqliteClient.cpp \
    ./qtdao/src/dbclients/SqlServerClient.cpp \
    ./qtdao/src/condition/ConditionConstraint.cpp \
    ./qtdao/src/condition/ConnectorData.cpp \
    ./qtdao/src/condition/EntityCondition.cpp \
    ./qtdao/src/condition/FunctionCondition.cpp
