/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>

class Test1 {
private:
    //主键
    qint64 id;
    //复合主键
    QString name;
    //浮点数字
    qreal number;
    //二进制
    QByteArray hex;

public:
    Test1() {
        name = "text";
        number = 10.0;
    }

    Test1(
        qint64 id,
        const QString& name,
        qreal number,
        const QByteArray& hex
    ) : id(id)
    , name(name)
    , number(number)
    , hex(hex)
    { }

public:
    struct Info {
        static int fieldSize() {
            return 4;
        }

        static QString getTableName() {
            return QStringLiteral("ts_test1");
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("id integer")
                << QStringLiteral("name text default 'text'")
                << QStringLiteral("number real default 10.0")
                << QStringLiteral("hex blob");
        }

        static QStringList getPrimaryKeys() {
            return QStringList() << "id" << "name";
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }
    };

public:
    //set 主键
    inline void setId(qint64 id) {this->id = id;}
    //get 主键
    inline qint64 getId() const {return id;}
    //set 复合主键
    inline void setName(const QString& name) {this->name = name;}
    //get 复合主键
    inline QString getName() const {return name;}
    //set 浮点数字
    inline void setNumber(qreal number) {this->number = number;}
    //get 浮点数字
    inline qreal getNumber() const {return number;}
    //set 二进制
    inline void setHex(const QByteArray& hex) {this->hex = hex;}
    //get 二进制
    inline QByteArray getHex() const {return hex;}
};
typedef QList<Test1> Test1List;
Q_DECLARE_METATYPE(Test1);