# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# ----------------------------------------------------


set(ENTITY_FILE_LIST
    ${CMAKE_CURRENT_LIST_DIR}/mysqlentityinclude.h
    ${CMAKE_CURRENT_LIST_DIR}/mysqlentityinclude.cpp

    ${CMAKE_CURRENT_LIST_DIR}/mysqltest1.h
    ${CMAKE_CURRENT_LIST_DIR}/mysqltest2.h
    ${CMAKE_CURRENT_LIST_DIR}/mysqltest3.h
    ${CMAKE_CURRENT_LIST_DIR}/mysqldefaulttestint.h
    ${CMAKE_CURRENT_LIST_DIR}/mysqldefaulttesttime.h
    ${CMAKE_CURRENT_LIST_DIR}/mysqldefaultteststr.h
)