# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# ----------------------------------------------------


HEADERS += ./mysqltest1.h \
    ./mysqltest2.h \
    ./mysqltest3.h \
    ./mysqldefaulttestint.h \
    ./mysqldefaulttesttime.h \
    ./mysqldefaultteststr.h \
    ./mysqlentityinclude.h
SOURCES += ./mysqlentityinclude.cpp
