/*This file is auto generated by DbEntityGenerator*/
#pragma once

#include <qobject.h>
#include <qvariant.h>
#include <qdatetime.h>

#include "condition/EntityField.h"

class MysqlTest3 {
private:
    //
    qint64 id;
    //绑定到MysqlTest1 id
    qint64 tbi1;
    //绑定到MysqlTest2 id
    qint64 tbi2;
    //
    QString name;
    //
    int size;
    //type tinyint
    char fTinyInt;
    //type small int
    short fSmallInt;
    //type medium int
    int fMediumInt;
    //type int(7)
    int fInt;
    //type big int
    qint64 fBigInt;
    //type float
    double fFloat;
    //type double
    double fDouble;
    //type decimal(6,4)
    double fDecimal;
    //type date
    QDate fDate;
    //type time
    QString fTime;
    //type date time
    QDateTime fDateTime;
    //type timestamp
    QDateTime fTimestamp;
    //type char
    QChar fChar;
    //type varchar(12)
    QString fVarChar;
    //type tiny blob
    QByteArray fTinyBlob;
    //type tiny text
    QString fTinyText;
    //type blob
    QByteArray fBlob;
    //type text
    QString fText;
    //type medium blob
    QByteArray fMediumBlob;
    //type medium text
    QString fMediumText;
    //type long blob
    QByteArray fLongBlob;
    //type long text
    QString fLongText;

    QHash<QString, QVariant> __extra;

public:
    MysqlTest3() {
        id = -1;
        tbi1 = -1;
        tbi2 = -1;
        fTinyInt = 0;
        fSmallInt = 0;
        fMediumInt = 0;
        fInt = 0;
        fBigInt = 0;
        fFloat = 0;
        fDouble = 0;
        fDecimal = 0;
        fDate = QDate();
        fTime = "00:00:00";
        fDateTime = QDateTime();
        fTimestamp = QDateTime();
        fChar = 'a';
        fVarChar = "a";
        fTinyBlob = "a";
        fTinyText = "a";
        fBlob = "a";
        fText = "a";
        fMediumBlob = "a";
        fMediumText = "a";
        fLongBlob = "a";
        fLongText = "a";
    }

    MysqlTest3(
        const qint64& tbi1,
        const qint64& tbi2,
        const QString& name,
        const int& size,
        const char& fTinyInt,
        const short& fSmallInt,
        const int& fMediumInt,
        const int& fInt,
        const qint64& fBigInt,
        const double& fFloat,
        const double& fDouble,
        const double& fDecimal,
        const QDate& fDate,
        const QString& fTime,
        const QDateTime& fDateTime,
        const QDateTime& fTimestamp,
        const QChar& fChar,
        const QString& fVarChar,
        const QByteArray& fTinyBlob,
        const QString& fTinyText,
        const QByteArray& fBlob,
        const QString& fText,
        const QByteArray& fMediumBlob,
        const QString& fMediumText,
        const QByteArray& fLongBlob,
        const QString& fLongText
    ) : tbi1(tbi1)
    , tbi2(tbi2)
    , name(name)
    , size(size)
    , fTinyInt(fTinyInt)
    , fSmallInt(fSmallInt)
    , fMediumInt(fMediumInt)
    , fInt(fInt)
    , fBigInt(fBigInt)
    , fFloat(fFloat)
    , fDouble(fDouble)
    , fDecimal(fDecimal)
    , fDate(fDate)
    , fTime(fTime)
    , fDateTime(fDateTime)
    , fTimestamp(fTimestamp)
    , fChar(fChar)
    , fVarChar(fVarChar)
    , fTinyBlob(fTinyBlob)
    , fTinyText(fTinyText)
    , fBlob(fBlob)
    , fText(fText)
    , fMediumBlob(fMediumBlob)
    , fMediumText(fMediumText)
    , fLongBlob(fLongBlob)
    , fLongText(fLongText)
    {
        id = -1;
    }

    MysqlTest3(
        const QString& name,
        const int& size
    ) : name(name)
    , size(size)
    {
        id = -1;
        tbi1 = -1;
        tbi2 = -1;
        fTinyInt = 0;
        fSmallInt = 0;
        fMediumInt = 0;
        fInt = 0;
        fBigInt = 0;
        fFloat = 0;
        fDouble = 0;
        fDecimal = 0;
        fDate = QDate();
        fTime = "00:00:00";
        fDateTime = QDateTime();
        fTimestamp = QDateTime();
        fChar = 'a';
        fVarChar = "a";
        fTinyBlob = "a";
        fTinyText = "a";
        fBlob = "a";
        fText = "a";
        fMediumBlob = "a";
        fMediumText = "a";
        fLongBlob = "a";
        fLongText = "a";
    }

    MysqlTest3(
        const qint64& tbi1,
        const qint64& tbi2,
        const QString& name,
        const int& size
    ) : tbi1(tbi1)
    , tbi2(tbi2)
    , name(name)
    , size(size)
    {
        id = -1;
        fTinyInt = 0;
        fSmallInt = 0;
        fMediumInt = 0;
        fInt = 0;
        fBigInt = 0;
        fFloat = 0;
        fDouble = 0;
        fDecimal = 0;
        fDate = QDate();
        fTime = "00:00:00";
        fDateTime = QDateTime();
        fTimestamp = QDateTime();
        fChar = 'a';
        fVarChar = "a";
        fTinyBlob = "a";
        fTinyText = "a";
        fBlob = "a";
        fText = "a";
        fMediumBlob = "a";
        fMediumText = "a";
        fLongBlob = "a";
        fLongText = "a";
    }

public:
    class Fields {
    public:
        EntityField<qint64> id = EntityField<qint64>("id", "ts_mysqltest3");
        EntityField<qint64> tbi1 = EntityField<qint64>("tbi1", "ts_mysqltest3");
        EntityField<qint64> tbi2 = EntityField<qint64>("tbi2", "ts_mysqltest3");
        EntityField<QString> name = EntityField<QString>("name", "ts_mysqltest3");
        EntityField<int> size = EntityField<int>("size", "ts_mysqltest3");
        EntityField<char> fTinyInt = EntityField<char>("fTinyInt", "ts_mysqltest3");
        EntityField<short> fSmallInt = EntityField<short>("fSmallInt", "ts_mysqltest3");
        EntityField<int> fMediumInt = EntityField<int>("fMediumInt", "ts_mysqltest3");
        EntityField<int> fInt = EntityField<int>("fInt", "ts_mysqltest3");
        EntityField<qint64> fBigInt = EntityField<qint64>("fBigInt", "ts_mysqltest3");
        EntityField<double> fFloat = EntityField<double>("fFloat", "ts_mysqltest3");
        EntityField<double> fDouble = EntityField<double>("fDouble", "ts_mysqltest3");
        EntityField<double> fDecimal = EntityField<double>("fDecimal", "ts_mysqltest3");
        EntityField<QDate> fDate = EntityField<QDate>("fDate", "ts_mysqltest3");
        EntityField<QString> fTime = EntityField<QString>("fTime", "ts_mysqltest3");
        EntityField<QDateTime> fDateTime = EntityField<QDateTime>("fDateTime", "ts_mysqltest3");
        EntityField<QDateTime> fTimestamp = EntityField<QDateTime>("fTimestamp", "ts_mysqltest3");
        EntityField<QChar> fChar = EntityField<QChar>("fChar", "ts_mysqltest3");
        EntityField<QString> fVarChar = EntityField<QString>("fVarChar", "ts_mysqltest3");
        EntityField<QByteArray> fTinyBlob = EntityField<QByteArray>("fTinyBlob", "ts_mysqltest3");
        EntityField<QString> fTinyText = EntityField<QString>("fTinyText", "ts_mysqltest3");
        EntityField<QByteArray> fBlob = EntityField<QByteArray>("fBlob", "ts_mysqltest3");
        EntityField<QString> fText = EntityField<QString>("fText", "ts_mysqltest3");
        EntityField<QByteArray> fMediumBlob = EntityField<QByteArray>("fMediumBlob", "ts_mysqltest3");
        EntityField<QString> fMediumText = EntityField<QString>("fMediumText", "ts_mysqltest3");
        EntityField<QByteArray> fLongBlob = EntityField<QByteArray>("fLongBlob", "ts_mysqltest3");
        EntityField<QString> fLongText = EntityField<QString>("fLongText", "ts_mysqltest3");

    protected:
        void reset(const QString& tbName) {
            id = EntityField<qint64>("id", tbName);
            tbi1 = EntityField<qint64>("tbi1", tbName);
            tbi2 = EntityField<qint64>("tbi2", tbName);
            name = EntityField<QString>("name", tbName);
            size = EntityField<int>("size", tbName);
            fTinyInt = EntityField<char>("fTinyInt", tbName);
            fSmallInt = EntityField<short>("fSmallInt", tbName);
            fMediumInt = EntityField<int>("fMediumInt", tbName);
            fInt = EntityField<int>("fInt", tbName);
            fBigInt = EntityField<qint64>("fBigInt", tbName);
            fFloat = EntityField<double>("fFloat", tbName);
            fDouble = EntityField<double>("fDouble", tbName);
            fDecimal = EntityField<double>("fDecimal", tbName);
            fDate = EntityField<QDate>("fDate", tbName);
            fTime = EntityField<QString>("fTime", tbName);
            fDateTime = EntityField<QDateTime>("fDateTime", tbName);
            fTimestamp = EntityField<QDateTime>("fTimestamp", tbName);
            fChar = EntityField<QChar>("fChar", tbName);
            fVarChar = EntityField<QString>("fVarChar", tbName);
            fTinyBlob = EntityField<QByteArray>("fTinyBlob", tbName);
            fTinyText = EntityField<QString>("fTinyText", tbName);
            fBlob = EntityField<QByteArray>("fBlob", tbName);
            fText = EntityField<QString>("fText", tbName);
            fMediumBlob = EntityField<QByteArray>("fMediumBlob", tbName);
            fMediumText = EntityField<QString>("fMediumText", tbName);
            fLongBlob = EntityField<QByteArray>("fLongBlob", tbName);
            fLongText = EntityField<QString>("fLongText", tbName);
        }
    };

    struct Info {
        enum {
            Attach = 1
        };

        static int fieldSize() {
            return 27;
        }

        static QString getTableName() {
            return QStringLiteral("ts_mysqltest3");
        }

        static QString getSourceName() {
            return getTableName();
        }

        static QString getTableEngine() {
            return QString();
        }

        static QStringList getFields() {
            return QStringList()
                << "id"
                << "tbi1"
                << "tbi2"
                << "name"
                << "size"
                << "fTinyInt"
                << "fSmallInt"
                << "fMediumInt"
                << "fInt"
                << "fBigInt"
                << "fFloat"
                << "fDouble"
                << "fDecimal"
                << "fDate"
                << "fTime"
                << "fDateTime"
                << "fTimestamp"
                << "fChar"
                << "fVarChar"
                << "fTinyBlob"
                << "fTinyText"
                << "fBlob"
                << "fText"
                << "fMediumBlob"
                << "fMediumText"
                << "fLongBlob"
                << "fLongText";
        }

        static QStringList getFieldsWithoutAutoIncrement() {
            return QStringList()
                << "tbi1"
                << "tbi2"
                << "name"
                << "size"
                << "fTinyInt"
                << "fSmallInt"
                << "fMediumInt"
                << "fInt"
                << "fBigInt"
                << "fFloat"
                << "fDouble"
                << "fDecimal"
                << "fDate"
                << "fTime"
                << "fDateTime"
                << "fTimestamp"
                << "fChar"
                << "fVarChar"
                << "fTinyBlob"
                << "fTinyText"
                << "fBlob"
                << "fText"
                << "fMediumBlob"
                << "fMediumText"
                << "fLongBlob"
                << "fLongText";
        }

        static QStringList getFieldsType() {
            return QStringList() 
                << QStringLiteral("id bigint primary key auto_increment comment ''")
                << QStringLiteral("tbi1 bigint default -1 comment '绑定到MysqlTest1 id'")
                << QStringLiteral("tbi2 bigint default -1 comment '绑定到MysqlTest2 id'")
                << QStringLiteral("name text comment ''")
                << QStringLiteral("size int comment ''")
                << QStringLiteral("fTinyInt tinyint default 0 comment 'type tinyint'")
                << QStringLiteral("fSmallInt smallint default 0 comment 'type small int'")
                << QStringLiteral("fMediumInt mediumint default 0 comment 'type medium int'")
                << QStringLiteral("fInt int(7) default 0 comment 'type int(7)'")
                << QStringLiteral("fBigInt bigint default 0 comment 'type big int'")
                << QStringLiteral("fFloat float default 0 comment 'type float'")
                << QStringLiteral("fDouble double default 0 comment 'type double'")
                << QStringLiteral("fDecimal decimal(6,4) default 0 comment 'type decimal(6,4)'")
                << QStringLiteral("fDate date comment 'type date'")
                << QStringLiteral("fTime time comment 'type time'")
                << QStringLiteral("fDateTime datetime comment 'type date time'")
                << QStringLiteral("fTimestamp timestamp comment 'type timestamp'")
                << QStringLiteral("fChar char default 'a' comment 'type char'")
                << QStringLiteral("fVarChar varchar(12) default 'a' comment 'type varchar(12)'")
                << QStringLiteral("fTinyBlob tinyblob comment 'type tiny blob'")
                << QStringLiteral("fTinyText tinytext comment 'type tiny text'")
                << QStringLiteral("fBlob blob comment 'type blob'")
                << QStringLiteral("fText text comment 'type text'")
                << QStringLiteral("fMediumBlob mediumblob comment 'type medium blob'")
                << QStringLiteral("fMediumText mediumtext comment 'type medium text'")
                << QStringLiteral("fLongBlob longblob comment 'type long blob'")
                << QStringLiteral("fLongText longtext comment 'type long text'");
        }

        static QStringList getPrimaryKeys() {
            return QStringList() << "id";
        }

        static QList<QStringList> getIndexFields() {
            return QList<QStringList>();
        }

        static QList<QStringList> getUniqueIndexFields() {
            return QList<QStringList>();
        }

        static bool isAutoIncrement(const QString& name) {
            return name == "id";
        }
    };

    struct Tool {
        static QVariantList getValueWithoutAutoIncrement(const MysqlTest3& entity) {
            return QVariantList()
                << entity.tbi1
                << entity.tbi2
                << entity.name
                << entity.size
                << entity.fTinyInt
                << entity.fSmallInt
                << entity.fMediumInt
                << entity.fInt
                << entity.fBigInt
                << entity.fFloat
                << entity.fDouble
                << entity.fDecimal
                << entity.fDate
                << entity.fTime
                << entity.fDateTime
                << entity.fTimestamp
                << entity.fChar
                << entity.fVarChar
                << entity.fTinyBlob
                << entity.fTinyText
                << entity.fBlob
                << entity.fText
                << entity.fMediumBlob
                << entity.fMediumText
                << entity.fLongBlob
                << entity.fLongText;
        }

        static QVariant getValueByName(const MysqlTest3& entity, const QString& target) {
            if (target == "id") {
                return entity.id;
            }
            if (target == "tbi1") {
                return entity.tbi1;
            }
            if (target == "tbi2") {
                return entity.tbi2;
            }
            if (target == "name") {
                return entity.name;
            }
            if (target == "size") {
                return entity.size;
            }
            if (target == "fTinyInt") {
                return entity.fTinyInt;
            }
            if (target == "fSmallInt") {
                return entity.fSmallInt;
            }
            if (target == "fMediumInt") {
                return entity.fMediumInt;
            }
            if (target == "fInt") {
                return entity.fInt;
            }
            if (target == "fBigInt") {
                return entity.fBigInt;
            }
            if (target == "fFloat") {
                return entity.fFloat;
            }
            if (target == "fDouble") {
                return entity.fDouble;
            }
            if (target == "fDecimal") {
                return entity.fDecimal;
            }
            if (target == "fDate") {
                return entity.fDate;
            }
            if (target == "fTime") {
                return entity.fTime;
            }
            if (target == "fDateTime") {
                return entity.fDateTime;
            }
            if (target == "fTimestamp") {
                return entity.fTimestamp;
            }
            if (target == "fChar") {
                return entity.fChar;
            }
            if (target == "fVarChar") {
                return entity.fVarChar;
            }
            if (target == "fTinyBlob") {
                return entity.fTinyBlob;
            }
            if (target == "fTinyText") {
                return entity.fTinyText;
            }
            if (target == "fBlob") {
                return entity.fBlob;
            }
            if (target == "fText") {
                return entity.fText;
            }
            if (target == "fMediumBlob") {
                return entity.fMediumBlob;
            }
            if (target == "fMediumText") {
                return entity.fMediumText;
            }
            if (target == "fLongBlob") {
                return entity.fLongBlob;
            }
            if (target == "fLongText") {
                return entity.fLongText;
            }
            return entity.__extra.value(target);
        }

        static void bindAutoIncrementId(MysqlTest3& entity, const QVariant& id) {
            entity.id = id.value<qint64>();
        }

        static void bindValue(MysqlTest3& entity, const QString& target, QVariant value) {
            if (target == "id") {
                entity.id = value.value<qint64>();
            } else if (target == "tbi1") {
                entity.tbi1 = value.value<qint64>();
            } else if (target == "tbi2") {
                entity.tbi2 = value.value<qint64>();
            } else if (target == "name") {
                entity.name = value.value<QString>();
            } else if (target == "size") {
                entity.size = value.value<int>();
            } else if (target == "fTinyInt") {
                entity.fTinyInt = value.value<char>();
            } else if (target == "fSmallInt") {
                entity.fSmallInt = value.value<short>();
            } else if (target == "fMediumInt") {
                entity.fMediumInt = value.value<int>();
            } else if (target == "fInt") {
                entity.fInt = value.value<int>();
            } else if (target == "fBigInt") {
                entity.fBigInt = value.value<qint64>();
            } else if (target == "fFloat") {
                entity.fFloat = value.value<double>();
            } else if (target == "fDouble") {
                entity.fDouble = value.value<double>();
            } else if (target == "fDecimal") {
                entity.fDecimal = value.value<double>();
            } else if (target == "fDate") {
                entity.fDate = value.value<QDate>();
            } else if (target == "fTime") {
                entity.fTime = value.value<QString>();
            } else if (target == "fDateTime") {
                entity.fDateTime = value.value<QDateTime>();
            } else if (target == "fTimestamp") {
                entity.fTimestamp = value.value<QDateTime>();
            } else if (target == "fChar") {
                entity.fChar = value.value<QChar>();
            } else if (target == "fVarChar") {
                entity.fVarChar = value.value<QString>();
            } else if (target == "fTinyBlob") {
                entity.fTinyBlob = value.value<QByteArray>();
            } else if (target == "fTinyText") {
                entity.fTinyText = value.value<QString>();
            } else if (target == "fBlob") {
                entity.fBlob = value.value<QByteArray>();
            } else if (target == "fText") {
                entity.fText = value.value<QString>();
            } else if (target == "fMediumBlob") {
                entity.fMediumBlob = value.value<QByteArray>();
            } else if (target == "fMediumText") {
                entity.fMediumText = value.value<QString>();
            } else if (target == "fLongBlob") {
                entity.fLongBlob = value.value<QByteArray>();
            } else if (target == "fLongText") {
                entity.fLongText = value.value<QString>();
            } else {
                entity.__putExtra(target, value);
            }
        }
    };

public:
    //
    inline void setId(const qint64& id) {this->id = id;}
    //
    inline qint64 getId() const {return id;}
    //set 绑定到MysqlTest1 id
    inline void setTbi1(const qint64& tbi1) {this->tbi1 = tbi1;}
    //get 绑定到MysqlTest1 id
    inline qint64 getTbi1() const {return tbi1;}
    //set 绑定到MysqlTest2 id
    inline void setTbi2(const qint64& tbi2) {this->tbi2 = tbi2;}
    //get 绑定到MysqlTest2 id
    inline qint64 getTbi2() const {return tbi2;}
    //
    inline void setName(const QString& name) {this->name = name;}
    //
    inline QString getName() const {return name;}
    //
    inline void setSize(const int& size) {this->size = size;}
    //
    inline int getSize() const {return size;}
    //set type tinyint
    inline void setFTinyInt(const char& fTinyInt) {this->fTinyInt = fTinyInt;}
    //get type tinyint
    inline char getFTinyInt() const {return fTinyInt;}
    //set type small int
    inline void setFSmallInt(const short& fSmallInt) {this->fSmallInt = fSmallInt;}
    //get type small int
    inline short getFSmallInt() const {return fSmallInt;}
    //set type medium int
    inline void setFMediumInt(const int& fMediumInt) {this->fMediumInt = fMediumInt;}
    //get type medium int
    inline int getFMediumInt() const {return fMediumInt;}
    //set type int(7)
    inline void setFInt(const int& fInt) {this->fInt = fInt;}
    //get type int(7)
    inline int getFInt() const {return fInt;}
    //set type big int
    inline void setFBigInt(const qint64& fBigInt) {this->fBigInt = fBigInt;}
    //get type big int
    inline qint64 getFBigInt() const {return fBigInt;}
    //set type float
    inline void setFFloat(const double& fFloat) {this->fFloat = fFloat;}
    //get type float
    inline double getFFloat() const {return fFloat;}
    //set type double
    inline void setFDouble(const double& fDouble) {this->fDouble = fDouble;}
    //get type double
    inline double getFDouble() const {return fDouble;}
    //set type decimal(6,4)
    inline void setFDecimal(const double& fDecimal) {this->fDecimal = fDecimal;}
    //get type decimal(6,4)
    inline double getFDecimal() const {return fDecimal;}
    //set type date
    inline void setFDate(const QDate& fDate) {this->fDate = fDate;}
    //get type date
    inline QDate getFDate() const {return fDate;}
    //set type time
    inline void setFTime(const QString& fTime) {this->fTime = fTime;}
    //get type time
    inline QString getFTime() const {return fTime;}
    //set type date time
    inline void setFDateTime(const QDateTime& fDateTime) {this->fDateTime = fDateTime;}
    //get type date time
    inline QDateTime getFDateTime() const {return fDateTime;}
    //set type timestamp
    inline void setFTimestamp(const QDateTime& fTimestamp) {this->fTimestamp = fTimestamp;}
    //get type timestamp
    inline QDateTime getFTimestamp() const {return fTimestamp;}
    //set type char
    inline void setFChar(const QChar& fChar) {this->fChar = fChar;}
    //get type char
    inline QChar getFChar() const {return fChar;}
    //set type varchar(12)
    inline void setFVarChar(const QString& fVarChar) {this->fVarChar = fVarChar;}
    //get type varchar(12)
    inline QString getFVarChar() const {return fVarChar;}
    //set type tiny blob
    inline void setFTinyBlob(const QByteArray& fTinyBlob) {this->fTinyBlob = fTinyBlob;}
    //get type tiny blob
    inline QByteArray getFTinyBlob() const {return fTinyBlob;}
    //set type tiny text
    inline void setFTinyText(const QString& fTinyText) {this->fTinyText = fTinyText;}
    //get type tiny text
    inline QString getFTinyText() const {return fTinyText;}
    //set type blob
    inline void setFBlob(const QByteArray& fBlob) {this->fBlob = fBlob;}
    //get type blob
    inline QByteArray getFBlob() const {return fBlob;}
    //set type text
    inline void setFText(const QString& fText) {this->fText = fText;}
    //get type text
    inline QString getFText() const {return fText;}
    //set type medium blob
    inline void setFMediumBlob(const QByteArray& fMediumBlob) {this->fMediumBlob = fMediumBlob;}
    //get type medium blob
    inline QByteArray getFMediumBlob() const {return fMediumBlob;}
    //set type medium text
    inline void setFMediumText(const QString& fMediumText) {this->fMediumText = fMediumText;}
    //get type medium text
    inline QString getFMediumText() const {return fMediumText;}
    //set type long blob
    inline void setFLongBlob(const QByteArray& fLongBlob) {this->fLongBlob = fLongBlob;}
    //get type long blob
    inline QByteArray getFLongBlob() const {return fLongBlob;}
    //set type long text
    inline void setFLongText(const QString& fLongText) {this->fLongText = fLongText;}
    //get type long text
    inline QString getFLongText() const {return fLongText;}
    //set temp data
    inline void __putExtra(const QString& key, const QVariant& extra) {this->__extra.insert(key, extra);}
    //get function select result, like get "as" field result
    inline QVariant __getExtra(const QString& key) const {return __extra.value(key);}
};
typedef QList<MysqlTest3> MysqlTest3List;
Q_DECLARE_METATYPE(MysqlTest3);