# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# ----------------------------------------------------


HEADERS += ./sqlitetest1.h \
    ./sqlitetest2.h \
    ./sqlitetest3.h \
    ./sqlitedefaulttestint.h \
    ./sqlitedefaultteststr.h \
    ./sqliteentityinclude.h
SOURCES += ./sqliteentityinclude.cpp
