# ----------------------------------------------------
# This file is generated by the vscode-qtdao.
# ----------------------------------------------------


set(ENTITY_FILE_LIST
    ${CMAKE_CURRENT_LIST_DIR}/sqliteentityinclude.h
    ${CMAKE_CURRENT_LIST_DIR}/sqliteentityinclude.cpp

    ${CMAKE_CURRENT_LIST_DIR}/sqlitetest1.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlitetest2.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlitetest3.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlitedefaulttestint.h
    ${CMAKE_CURRENT_LIST_DIR}/sqlitedefaultteststr.h
)